s3:
  bucket_name: pharma-usecase1
  file_path: 'timeseries/historical_demand_mlops.csv'

feature-store:
  lookup_key: "date"
  table_name: "timeseries"
  online_table_name: "xgboost_online_table"


Mlflow:
    experiment_name: "/Shared/dbx/Timeseries"
    run_name: "sarimax"
    register_model: "timeseries_model"
    artifact_path: "timeseries_prediction"
    

train_exog: ['Quarter', 'Week_Number','Month', 'Year', 'day', 'dayofyear', 'weekday',
                'is_month_start', 'is_month_end','contri_week_quarter','SI_Quarter_week']

# Terraform:
#      json: "timeseries/terraform.json"
