s3:
  bucket_name: pharma-usecase1
  file_path: 'timeseries/historical_demand_mlops.csv'

feature-store:
  lookup_key: "date"
  table_name: "system.xgbtimeseries2"
  online_table_name: "xgboost_online_table"


Mlflow:
    experiment_name: "/Shared/dbx/xgboost_mlops"
    run_name: "ForecastAutoReg"
    register_model: "Xgboost_model"
    artifact_path: "timeseries_prediction"
    

train_exog: ['Quarter', 'Week_Number','Month', 'Year', 'day', 'dayofyear', 'weekday',
                'is_month_start', 'is_month_end','contri_week_quarter','SI_Quarter_week']

xgboost:
      max_depth: 3
      n_estimators: 200 
      learning_rate: 0.1
      alpha: 0.1
      lags: 5

Terraform:
     json: "timeseries/terraform.json"
